# Generated by Django 3.1.7 on 2021-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='./static/images/default.png', upload_to='./static/images'),
        ),
    ]
