# Generated by Django 3.1.7 on 2021-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='confirmedmail',
            name='mails_list',
            field=models.CharField(max_length=30),
        ),
    ]
