# Generated by Django 3.1.7 on 2021-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.CharField(choices=[('worker', 'Worker'), ('admin', 'Admin'), ('Chief', 'Chief')], default=None, max_length=15),
        ),
    ]
