# Generated by Django 3.1.7 on 2021-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accept_email',
            field=models.BooleanField(default=True, verbose_name='получать e-mails'),
        ),
    ]
