# Generated by Django 3.1.7 on 2021-04-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210425_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='FinalProject/static/images/default.png', upload_to='./static/images'),
        ),
    ]
