# Generated by Django 3.1.7 on 2021-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210421_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept_email',
            field=models.BooleanField(default=True),
        ),
    ]
