# Generated by Django 3.1.7 on 2021-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210329_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', height_field=50, null=True, upload_to='', width_field=50),
        ),
    ]
