# Generated by Django 3.1.7 on 2021-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210329_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/static/images/default.png', null=True, upload_to='users/static/images'),
        ),
    ]
