# Generated by Django 3.1.7 on 2021-04-12 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок статьи')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='заглавное изображение')),
                ('article_type', models.CharField(choices=[('company_news', 'новости компании'), ('news', 'новости'), ('library', 'база знаний')], default='news', max_length=15, verbose_name='тип статьи')),
                ('source', models.URLField(blank=True, null=True, verbose_name='источник')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='параграф')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='testing.article', verbose_name='статья')),
            ],
            options={
                'verbose_name': 'параграф',
                'verbose_name_plural': 'параграфы',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='новый тест', max_length=255, verbose_name='название теста')),
                ('description', models.CharField(default='', max_length=255, verbose_name='описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='testing.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата назначения')),
                ('date_expired', models.DateTimeField(null=True, verbose_name='пройти до')),
                ('time_for_one_question', models.PositiveIntegerField(blank=True, null=True, verbose_name='среднее время на вопрос (сек.)')),
                ('target_score', models.PositiveIntegerField(default=90, verbose_name='проходной балл')),
                ('result_score', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='набранный балл')),
                ('complete', models.BooleanField(default=False, verbose_name='завершен')),
                ('test_case_result', models.CharField(blank=True, max_length=20, null=True, verbose_name='итоговый результат')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testcase', verbose_name='тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'тест для сотрудников',
                'verbose_name_plural': 'тесты для сотрудников',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_tests_passed', models.PositiveIntegerField(default=0, verbose_name='количество пройденных тестов')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='общий балл за тесты')),
                ('average_score', models.FloatField(default=0, verbose_name='средний балл')),
                ('average_rating', models.FloatField(default=0, verbose_name='рейтинг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'прогресс сотрудника',
                'verbose_name_plural': 'прогресс сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('radio', 'один ответ'), ('checkbox', 'несколько ответов')], default='radio', max_length=8, verbose_name='тип ответов')),
                ('text', models.CharField(max_length=255, verbose_name='текст вопроса')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='testing.testcase', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParagraphImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='testing.paragraph', verbose_name='для параграфа')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.category', verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='текст ответа')),
                ('is_right', models.BooleanField(default=False, verbose_name='верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='testing.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
                'ordering': ['id'],
            },
        ),
    ]
