# Generated by Django 3.1.7 on 2021-04-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_paragraphyoutubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraphyoutubevideo',
            options={'verbose_name': 'видео с Youtube', 'verbose_name_plural': 'видео с Youtube'},
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, default='static/icons/new_info.jpg', upload_to='', verbose_name='заглавное изображение'),
        ),
    ]
