# Generated by Django 3.1.7 on 2021-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20210405_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestcase',
            name='time_for_one_question',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='среднее время на вопрос (сек.)'),
        ),
    ]
