# Generated by Django 3.1.7 on 2021-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20210414_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphyoutubevideo',
            name='source',
            field=models.URLField(null=True, verbose_name='ссылка на видео'),
        ),
    ]
