# Generated by Django 3.1.7 on 2021-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_auto_20210418_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphyoutubevideo',
            name='source',
            field=models.URLField(help_text='напр. https://www.youtube.com/watch?v=SX_9gC5_S0Q&ab_channel=GeekHubck', max_length=255, null=True, verbose_name='ссылка на видео'),
        ),
    ]
