# Generated by Django 3.1.7 on 2021-04-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20210418_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphyoutubevideo',
            name='source',
            field=models.URLField(help_text='напр. https://www.youtube.com/watch?v=Geek&ab_channel=Hub', max_length=255, null=True, verbose_name='ссылка на видео'),
        ),
    ]
